[package]
name = "onekeepass-core"
version = "0.16.0"
authors = ["jeyasankar"]
edition = "2021"

[dependencies]
argon2-sys = "0.1.0"

# RustCrypto https://github.com/RustCrypto
sha1 = "0.10.6"
sha2 = "0.10.8"
hmac = "0.12.1"

aes = "0.7.4"
block-modes = "0.8.1" 
chacha20 = "0.7.1"
cipher = "0.3.0"
aes-gcm = "0.10.2"
rand = "0.8.5"
rand_chacha = "0.3.1"

secstr = "0.5.1"

data-encoding = "2.5.0"
## TODO: Replace base64 with data-encoding crate
base64 = "0.21.4"
url = "2.5.2"
urlencoding = "2.1.3"

uuid = { version = "1.7.0", features = ["serde", "v4","macro-diagnostics"] }
chrono =  {version = "0.4.38", features = ["serde"]}
chrono-tz = "0.8.1"

flate2 = {version = "1.0", features = ["zlib"]} 

slice_as_array = "1.1.0"
log = "0.4.17"
hex-literal = "0.3.1"
hex = "0.4.3"
once_cell = "1.18.0"
thiserror = "1.0.57"
regex = "1.10.5"
lazy_static = "1.4.0"

tokio = { version = "1", features = [ "time" ,"rt", "rt-multi-thread","sync"] }

serde = { version = "1.0.137", features = [ "derive" ]}
serde_json = "1.0.81"
rmp-serde = "1.1.0" 
cfg-if = "1.0"

quick-xml = "0.30.0"
## Removed quick_xml_023 use 
## quick_xml_023 = { package = "quick-xml", version = "0.23.0" }

## SFTP
russh-sftp = "2.0.5"
russh = "0.45"
russh-keys = "0.45"
async-trait = "0.1"

## WebDav 
## reqwest_dav = "0.1.13"  - This did not build for android because of Openssl dependency

## The following two together works for ios and android build 
## Openssl is used for android and rustls for ios
#reqwest = { version = "0.12", default-features = false, features = ["native-tls-vendored"] }
#reqwest_dav = {version = "0.1.13", default-features = false }


## This works for ios and android as it uses rustls 
reqwest_dav = {version = "0.1.13", default-features = false,features = ["rustls-tls"]}


## rusqlite = { version = "0.32.0", features = ["bundled"] }

[target."cfg(any(target_os = \"linux\", target_os = \"macos\", target_os = \"windows\"))".dependencies]
botan = {version = "0.10.7", features = ["vendored"] }

[target.'cfg(target_os = "ios")'.dependencies]
#botan = {version = "0.10.7", features = ["botan3"] } 
botan = {version = "0.10.7", features = ["vendored"] }

[target.'cfg(all(target_os = "android", target_arch = "aarch64"))'.dependencies]
botan = {version = "0.10.7", features = ["vendored"] }

[dependencies.passwords]
version = "*"
features = ["common-password"]

[dev-dependencies]
env_logger = "0.8.4"
mockall = "0.10.2"
rstest = "0.18.1"



